---
substitutions:
  device_name: 'hyperserialesp32'
  project_version: '1.0'
  device_description: 'High speed 2Mb USB serial port LED strip driver using ESP32 devices. Port of my HyperSerialEsp8266 for ESP32 + multisegment/multithreading support.'
  espboard: 'esp32dev' # or use lolin_s2_mini

external_components:
  - source:
      type: git
      url: https://github.com/bruvv/HyperSerialESP32
      ref: master
    components: [hyperserialesp32]

esphome:
  name: '${device_name}'
  comment: '${device_description}'
  platformio_options:
    build_flags:
      - '-DNEOPIXEL_RGBW -DCOLD_WHITE -DDATA_PIN=2 -DSERIALCOM_SPEED=2000000'

esp32:
  board: '${espboard}'
  framework:
    type: arduino
    version: 2.0.6
    platform_version: 5.3.0

# ota:
#   safe_mode: true
#   reboot_timeout: 10min
#   num_attempts: 5

# wifi:
#   ssid: !secret wifi_ssid
#   password: !secret wifi_password

logger:
